package org.pjdbc.drivers;

import java.sql.*;

import org.pjdbc.annotations.DriverCapability;
import org.pjdbc.annotations.DriverParameter;
import org.pjdbc.annotations.DriverParameter.ParameterType;
import org.pjdbc.sql.*;

@DriverCapability(
    prefix = "filter",
    description = "Transforms SQL statements using a configurable JdbcTransformer",
    capabilities = {"transformation", "filtering"}
)
@DriverParameter(name = "class", type = ParameterType.STRING,
    description = "Fully qualified class name of JdbcTransformer implementation")
public class FilterDriver extends AbstractProxyDriver {
    static {try {DriverManager.registerDriver(new FilterDriver());} catch (Exception e) {throw new RuntimeException(e);}}

    protected ThreadLocal<JdbcTransformer> transformer =
        ThreadLocal.withInitial(() -> new AbstractJdbcTransformer() {});

    protected boolean acceptsSubProtocol (String subprotocol) {
        return "filter".equals(subprotocol);}

    protected Statement proxyStatement (Statement delegate, Connection conn) throws SQLException {
	final AbstractProxyDriver driver = this;
        final JdbcTransformer xformer = transformer.get();
        return new AbstractStatement(delegate, conn) {
	    @Override
	    protected ResultSet wrap (ResultSet r) throws SQLException {
		return driver.proxyResultSet(this, r);}
            public void addBatch (String sql) throws SQLException {
                super.addBatch(xformer.transformSql(sql));}
            public boolean execute (String sql) throws SQLException {
                return super.execute(xformer.transformSql(sql));}
            public boolean execute (String sql, int[] columnIndexes) throws SQLException {
                return super.execute(xformer.transformSql(sql), columnIndexes);}
            public boolean execute (String sql, String[] columnNames) throws SQLException {
                return super.execute(xformer.transformSql(sql), columnNames);}
            public ResultSet executeQuery (String sql) throws SQLException {
                return super.executeQuery(xformer.transformSql(sql));}
            public int executeUpdate (String sql) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql));}
            public int executeUpdate (String sql, int autoGeneratedKeys) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql), autoGeneratedKeys);}
            public int executeUpdate (String sql, int[] columnIndexes) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql), columnIndexes);}
            public int executeUpdate (String sql, String[] columnNames) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql), columnNames);}};}

    /**
     * Get the current transformer for this thread.
     * @return the JdbcTransformer used for SQL transformation
     */
    public JdbcTransformer getTransformer() {
        return transformer.get();}

    /**
     * Set the transformer for SQL transformation for this thread.
     * @param transformer the JdbcTransformer to use
     */
    public void setTransformer(JdbcTransformer transformer) {
        this.transformer.set(transformer);}}
