package org.pjdbc.drivers;

import java.sql.*;
import org.pjdbc.sql.*;

public class FilterDriver extends AbstractProxyDriver {
    static {try {DriverManager.registerDriver(new FilterDriver());} catch (Exception e) {throw new RuntimeException(e);}}

    /**
     * Legacy Filter interface for SQL transformation.
     * @deprecated Use {@link JdbcTransformer} instead for more comprehensive transformation support.
     */
    @Deprecated
    public static interface Filter {
        public String apply (String sql);}

    /**
     * Legacy abstract Filter implementation.
     * @deprecated Use {@link AbstractJdbcTransformer} instead.
     */
    @Deprecated
    public static abstract class AbstractFilter implements Filter {
        public String apply (String sql) {return sql;}}

    /**
     * Adapter that wraps a legacy Filter as a JdbcTransformer.
     */
    private static class FilterAdapter extends AbstractJdbcTransformer {
        private final Filter filter;

        FilterAdapter(Filter filter) {
            this.filter = filter;
        }

        @Override
        public String transformSql(String sql) throws SQLException {
            return filter.apply(sql);
        }
    }

    protected JdbcTransformer transformer = new AbstractJdbcTransformer() {};

    protected boolean acceptsSubProtocol (String subprotocol) {
        return "filter".equals(subprotocol);}

    protected Statement proxyStatement (Statement delegate, Connection conn) throws SQLException {
        final JdbcTransformer xformer = transformer;
        return new AbstractStatement(delegate, conn) {
            public void addBatch (String sql) throws SQLException {
                super.addBatch(xformer.transformSql(sql));}
            public boolean execute (String sql) throws SQLException {
                return super.execute(xformer.transformSql(sql));}
            public boolean execute (String sql, int[] columnIndexes) throws SQLException {
                return super.execute(xformer.transformSql(sql), columnIndexes);}
            public boolean execute (String sql, String[] columnNames) throws SQLException {
                return super.execute(xformer.transformSql(sql), columnNames);}
            public ResultSet executeQuery (String sql) throws SQLException {
                return super.executeQuery(xformer.transformSql(sql));}
            public int executeUpdate (String sql) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql));}
            public int executeUpdate (String sql, int autoGeneratedKeys) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql), autoGeneratedKeys);}
            public int executeUpdate (String sql, int[] columnIndexes) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql), columnIndexes);}
            public int executeUpdate (String sql, String[] columnNames) throws SQLException {
                return super.executeUpdate(xformer.transformSql(sql), columnNames);}};}

    /**
     * Get the current transformer.
     * @return the JdbcTransformer used for SQL transformation
     */
    public JdbcTransformer getTransformer() {
        return transformer;}

    /**
     * Set the transformer for SQL transformation.
     * @param transformer the JdbcTransformer to use
     */
    public void setTransformer(JdbcTransformer transformer) {
        this.transformer = transformer;}

    /**
     * Get the current filter as a legacy Filter.
     * @deprecated Use {@link #getTransformer()} instead.
     * @return the Filter, or null if a non-Filter transformer is set
     */
    @Deprecated
    public Filter getFilter () {
        if (transformer instanceof FilterAdapter fa) {
            return fa.filter;
        }
        return null;}

    /**
     * Set the filter using a legacy Filter.
     * @deprecated Use {@link #setTransformer(JdbcTransformer)} instead.
     * @param filter the Filter to use for SQL transformation
     */
    @Deprecated
    public void setFilter (Filter filter) {
        this.transformer = new FilterAdapter(filter);}}
