package org.pjdbc.drivers;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

import org.pjdbc.annotations.DriverCapability;
import org.pjdbc.sql.AbstractProxyDriver;
import org.pjdbc.sql.AbstractStatement;

/**
 * Discards all SQL operations without executing them.
 *
 * <p>SinkDriver is useful for:
 * <ul>
 *   <li>Benchmarking driver overhead without database I/O</li>
 *   <li>Testing connection logic without a real database</li>
 *   <li>Dry-run scenarios where SQL should be generated but not executed</li>
 * </ul>
 *
 * <p>All execute methods return success without actually running SQL.
 * Query methods return null ResultSets.
 *
 * <p>URL format: {@code jdbc:sink:jdbc:target:...}
 *
 * <p>Example:
 * <pre>
 * jdbc:sink:jdbc:postgresql://localhost/mydb
 * </pre>
 */
@DriverCapability(
    prefix = "sink",
    description = "Discards all SQL operations",
    capabilities = {"testing"},
    terminal = false
)
public class SinkDriver extends AbstractProxyDriver {

    static {
        try {
            DriverManager.registerDriver(new SinkDriver());
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }

    @Override
    protected boolean acceptsSubProtocol(String subprotocol) {
        return "sink".equals(subprotocol);
    }

    @Override
    protected Statement proxyStatement(Statement delegate, Connection conn) throws SQLException {
        final AbstractProxyDriver driver = this;
        return new AbstractStatement(delegate, conn) {
            @Override
            protected ResultSet wrap(ResultSet r) throws SQLException {
                return driver.proxyResultSet(this, r);
            }

            @Override
            public void addBatch(String sql) throws SQLException {
                // Intentionally empty - SinkDriver absorbs all operations
            }

            @Override
            public boolean execute(String sql) throws SQLException {
                return true;
            }

            @Override
            public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
                return true;
            }

            @Override
            public boolean execute(String sql, int[] columnIndexes) throws SQLException {
                return true;
            }

            @Override
            public boolean execute(String sql, String[] columnNames) throws SQLException {
                return true;
            }

            // Intentionally returns null - SinkDriver absorbs all operations
            @Override
            @SuppressWarnings("all")
            public ResultSet executeQuery(String sql) throws SQLException {
                return null;
            }

            @Override
            public int executeUpdate(String sql) throws SQLException {
                return 0;
            }

            @Override
            public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
                return 0;
            }

            @Override
            public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
                return 0;
            }

            @Override
            public int executeUpdate(String sql, String[] columnNames) throws SQLException {
                return 0;
            }
        };
    }
}
