package org.pjdbc.sql;

import java.sql.*;
import java.util.*;

public abstract class AbstractStatement extends AbstractWrapper implements Statement {
    private Connection conn;
    private List<Statement> delegates = new ArrayList<Statement>();

    /**
     * Strategy for merging results from multiple delegate statements.
     */
    public enum MergeStrategy {
        /** Return result from first (primary) delegate only */
        FIRST,
        /** Sum all update counts */
        SUM,
        /** Return minimum update count (conservative) */
        MIN,
        /** Return maximum update count */
        MAX
    }

    private MergeStrategy mergeStrategy = MergeStrategy.FIRST;

    protected List<Statement> getStatements() {
        return delegates;
    }

    protected ResultSet wrap(ResultSet r) throws SQLException {
        return new AbstractResultSet(this, r) {};
    }

    public MergeStrategy getMergeStrategy() {
        return mergeStrategy;
    }

    public void setMergeStrategy(MergeStrategy strategy) {
        this.mergeStrategy = strategy;
    }

    protected int mergeUpdateCounts(List<Integer> counts) {
        if (counts.isEmpty()) return 0;
        switch (mergeStrategy) {
            case SUM:
                return counts.stream().mapToInt(Integer::intValue).sum();
            case MIN:
                return counts.stream().mapToInt(Integer::intValue).min().orElse(0);
            case MAX:
                return counts.stream().mapToInt(Integer::intValue).max().orElse(0);
            case FIRST:
            default:
                return counts.get(0);
        }
    }

    public AbstractStatement(Statement stmt, Connection conn) throws SQLException {
        super(stmt);
        delegates.add(stmt);
        this.conn = conn;
    }

    public AbstractStatement(Statement[] stmts, Connection conn) throws SQLException {
        super(stmts);
        delegates = Arrays.asList(stmts);
        this.conn = conn;
    }

    @Override
    public Connection getConnection() throws SQLException {
        return conn;
    }

    @Override
    public ResultSet executeQuery(String sql) throws SQLException {
        ArrayList<ResultSet> rsets = new ArrayList<ResultSet>();
        for (Statement s : getStatements()) {
            rsets.add(s.executeQuery(sql));
        }
        for (ResultSet r : rsets) {
            return wrap(r);
        }
        throw new SQLException();
    }

    @Override
    public ResultSet getGeneratedKeys() throws SQLException {
        for (Statement s : getStatements()) {
            return wrap(s.getGeneratedKeys());
        }
        throw new SQLException();
    }

    @Override
    public ResultSet getResultSet() throws SQLException {
        for (Statement s : getStatements()) {
            return wrap(s.getResultSet());
        }
        throw new SQLException();
    }

    @Override
    public SQLWarning getWarnings() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getWarnings();
        }
        throw new SQLException();
    }

    @Override
    public boolean execute(String sql) throws SQLException {
        Boolean first = null;
        for (Statement s : getStatements()) {
            boolean r = s.execute(sql);
            if (first == null) first = r;
        }
        if (first != null) return first;
        throw new SQLException();
    }

    @Override
    public boolean execute(String sql, String[] columnNames) throws SQLException {
        Boolean first = null;
        for (Statement s : getStatements()) {
            boolean r = s.execute(sql, columnNames);
            if (first == null) first = r;
        }
        if (first != null) return first;
        throw new SQLException();
    }

    @Override
    public boolean execute(String sql, int autoGeneratedKeys) throws SQLException {
        Boolean first = null;
        for (Statement s : getStatements()) {
            boolean r = s.execute(sql, autoGeneratedKeys);
            if (first == null) first = r;
        }
        if (first != null) return first;
        throw new SQLException();
    }

    @Override
    public boolean execute(String sql, int[] columnIndexes) throws SQLException {
        Boolean first = null;
        for (Statement s : getStatements()) {
            boolean r = s.execute(sql, columnIndexes);
            if (first == null) first = r;
        }
        if (first != null) return first;
        throw new SQLException();
    }

    @Override
    public boolean getMoreResults() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getMoreResults();
        }
        throw new SQLException();
    }

    @Override
    public boolean getMoreResults(int current) throws SQLException {
        for (Statement s : getStatements()) {
            return s.getMoreResults(current);
        }
        throw new SQLException();
    }

    @Override
    public boolean isCloseOnCompletion() throws SQLException {
        for (Statement s : getStatements()) {
            return s.isCloseOnCompletion();
        }
        throw new SQLException();
    }

    @Override
    public boolean isClosed() throws SQLException {
        for (Statement s : getStatements()) {
            return s.isClosed();
        }
        throw new SQLException();
    }

    @Override
    public boolean isPoolable() throws SQLException {
        for (Statement s : getStatements()) {
            return s.isPoolable();
        }
        throw new SQLException();
    }

    @Override
    public int executeUpdate(String sql) throws SQLException {
        List<Integer> counts = new ArrayList<>();
        for (Statement s : getStatements()) {
            counts.add(s.executeUpdate(sql));
        }
        if (!counts.isEmpty()) return mergeUpdateCounts(counts);
        throw new SQLException();
    }

    @Override
    public int executeUpdate(String sql, String[] columnNames) throws SQLException {
        List<Integer> counts = new ArrayList<>();
        for (Statement s : getStatements()) {
            counts.add(s.executeUpdate(sql, columnNames));
        }
        if (!counts.isEmpty()) return mergeUpdateCounts(counts);
        throw new SQLException();
    }

    @Override
    public int executeUpdate(String sql, int autoGeneratedKeys) throws SQLException {
        List<Integer> counts = new ArrayList<>();
        for (Statement s : getStatements()) {
            counts.add(s.executeUpdate(sql, autoGeneratedKeys));
        }
        if (!counts.isEmpty()) return mergeUpdateCounts(counts);
        throw new SQLException();
    }

    @Override
    public int executeUpdate(String sql, int[] columnIndexes) throws SQLException {
        List<Integer> counts = new ArrayList<>();
        for (Statement s : getStatements()) {
            counts.add(s.executeUpdate(sql, columnIndexes));
        }
        if (!counts.isEmpty()) return mergeUpdateCounts(counts);
        throw new SQLException();
    }

    @Override
    public int getFetchDirection() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getFetchDirection();
        }
        throw new SQLException();
    }

    @Override
    public int getFetchSize() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getFetchSize();
        }
        throw new SQLException();
    }

    @Override
    public int getMaxFieldSize() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getMaxFieldSize();
        }
        throw new SQLException();
    }

    @Override
    public int getMaxRows() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getMaxRows();
        }
        throw new SQLException();
    }

    @Override
    public int getQueryTimeout() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getQueryTimeout();
        }
        throw new SQLException();
    }

    @Override
    public int getResultSetConcurrency() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getResultSetConcurrency();
        }
        throw new SQLException();
    }

    @Override
    public int getResultSetHoldability() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getResultSetHoldability();
        }
        throw new SQLException();
    }

    @Override
    public int getResultSetType() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getResultSetType();
        }
        throw new SQLException();
    }

    @Override
    public int getUpdateCount() throws SQLException {
        for (Statement s : getStatements()) {
            return s.getUpdateCount();
        }
        throw new SQLException();
    }

    @Override
    public int[] executeBatch() throws SQLException {
        int[] first = null;
        for (Statement s : getStatements()) {
            int[] r = s.executeBatch();
            if (first == null) first = r;
        }
        if (first != null) return first;
        throw new SQLException();
    }

    @Override
    public void addBatch(String sql) throws SQLException {
        for (Statement s : getStatements()) {
            s.addBatch(sql);
        }
    }

    @Override
    public void cancel() throws SQLException {
        for (Statement s : getStatements()) {
            s.cancel();
        }
    }

    @Override
    public void clearBatch() throws SQLException {
        for (Statement s : getStatements()) {
            s.clearBatch();
        }
    }

    @Override
    public void clearWarnings() throws SQLException {
        for (Statement s : getStatements()) {
            s.clearWarnings();
        }
    }

    @Override
    public void close() throws SQLException {
        for (Statement s : getStatements()) {
            s.close();
        }
    }

    @Override
    public void closeOnCompletion() throws SQLException {
        for (Statement s : getStatements()) {
            s.closeOnCompletion();
        }
    }

    @Override
    public void setCursorName(String name) throws SQLException {
        for (Statement s : getStatements()) {
            s.setCursorName(name);
        }
    }

    @Override
    public void setEscapeProcessing(boolean enable) throws SQLException {
        for (Statement s : getStatements()) {
            s.setEscapeProcessing(enable);
        }
    }

    @Override
    public void setFetchDirection(int direction) throws SQLException {
        for (Statement s : getStatements()) {
            s.setFetchDirection(direction);
        }
    }

    @Override
    public void setFetchSize(int rows) throws SQLException {
        for (Statement s : getStatements()) {
            s.setFetchSize(rows);
        }
    }

    @Override
    public void setMaxFieldSize(int max) throws SQLException {
        for (Statement s : getStatements()) {
            s.setMaxFieldSize(max);
        }
    }

    @Override
    public void setMaxRows(int max) throws SQLException {
        for (Statement s : getStatements()) {
            s.setMaxRows(max);
        }
    }

    @Override
    public void setPoolable(boolean poolable) throws SQLException {
        for (Statement s : getStatements()) {
            s.setPoolable(poolable);
        }
    }

    @Override
    public void setQueryTimeout(int seconds) throws SQLException {
        for (Statement s : getStatements()) {
            s.setQueryTimeout(seconds);
        }
    }
}
