package org.pjdbc.sql;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.DriverPropertyInfo;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.Properties;

import org.pjdbc.validation.CompositionValidator;

/**
 * Base class for PJDBC proxy drivers that wrap and delegate to other JDBC drivers.
 *
 * <p>This class provides the core infrastructure for creating proxy drivers that can
 * intercept and modify JDBC operations. Subclasses override specific methods to
 * implement custom behavior such as SQL transformation, connection routing, or
 * operation logging.
 *
 * <p>Key extension points:
 * <ul>
 *   <li>{@link #acceptsSubProtocol(String)} - Define which URL prefix this driver handles</li>
 *   <li>{@link #proxyConnection(Connection, String, Properties, Driver)} - Customize connection wrapping</li>
 *   <li>{@link #proxyStatement(Statement, Connection)} - Customize statement wrapping</li>
 *   <li>{@link #proxyPreparedStatement(PreparedStatement, Connection)} - Customize prepared statement wrapping</li>
 * </ul>
 */
public abstract class AbstractProxyDriver extends AbstractDriver {

    protected boolean acceptsSubName(String subname) {
        try {
            return DriverManager.getDriver(subname) != null;
        } catch (Exception e) {
            // Driver not found
        }
        return false;
    }

    protected Connection proxyConnection(Connection conn, String url, Properties info, Driver driver) throws SQLException {
        return new AbstractConnection(conn, this, url, info) {
            @Override
            public Statement createStatement() throws SQLException {
                return proxyStatement(getDelegate().createStatement(), this);
            }

            @Override
            public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
                return proxyStatement(getDelegate().createStatement(resultSetType, resultSetConcurrency), this);
            }

            @Override
            public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
                return proxyStatement(getDelegate().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), this);
            }

            @Override
            public CallableStatement prepareCall(String sql) throws SQLException {
                return proxyCallableStatement(getDelegate().prepareCall(sql), this);
            }

            @Override
            public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
                return proxyCallableStatement(getDelegate().prepareCall(sql, resultSetType, resultSetConcurrency), this);
            }

            @Override
            public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
                return proxyCallableStatement(getDelegate().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this);
            }

            @Override
            public PreparedStatement prepareStatement(String sql) throws SQLException {
                return proxyPreparedStatement(getDelegate().prepareStatement(sql), this);
            }

            @Override
            public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
                return proxyPreparedStatement(getDelegate().prepareStatement(sql, autoGeneratedKeys), this);
            }

            @Override
            public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
                return proxyPreparedStatement(getDelegate().prepareStatement(sql, columnIndexes), this);
            }

            @Override
            public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
                return proxyPreparedStatement(getDelegate().prepareStatement(sql, resultSetType, resultSetConcurrency), this);
            }

            @Override
            public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
                return proxyPreparedStatement(getDelegate().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this);
            }

            @Override
            public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
                return proxyPreparedStatement(getDelegate().prepareStatement(sql, columnNames), this);
            }
        };
    }

    protected Connection proxyConnection(Connection delegate, String url, Properties info, List<Connection> delegates) throws SQLException {
        return new AbstractConnection(delegate, this, url, info) {};
    }

    protected Connection proxyConnection(String url, Properties info, Connection[] delegates) throws SQLException {
        return new AbstractConnection(delegates, this, url, info) {};
    }

    protected Statement proxyStatement(Statement delegate, Connection conn) throws SQLException {
        final AbstractProxyDriver driver = this;
        return new AbstractStatement(delegate, conn) {
            @Override
            protected ResultSet wrap(ResultSet r) throws SQLException {
                return driver.proxyResultSet(this, r);
            }
        };
    }

    protected CallableStatement proxyCallableStatement(CallableStatement delegate, Connection conn) throws SQLException {
        final AbstractProxyDriver driver = this;
        return new AbstractCallableStatement(delegate, conn) {
            @Override
            protected ResultSet wrap(ResultSet r) throws SQLException {
                return driver.proxyResultSet(this, r);
            }
        };
    }

    protected PreparedStatement proxyPreparedStatement(PreparedStatement delegate, Connection conn) throws SQLException {
        final AbstractProxyDriver driver = this;
        return new AbstractPreparedStatement(delegate, conn) {
            @Override
            protected ResultSet wrap(ResultSet r) throws SQLException {
                return driver.proxyResultSet(this, r);
            }
        };
    }

    /**
     * Proxy a PreparedStatement with access to the original SQL.
     * Override this method when you need to recreate the statement (e.g., on connection failure).
     * The default implementation ignores the SQL and delegates to {@link #proxyPreparedStatement(PreparedStatement, Connection)}.
     *
     * @param delegate the delegate PreparedStatement
     * @param conn the connection
     * @param sql the SQL used to prepare the statement
     * @return the proxied PreparedStatement
     * @throws SQLException if an error occurs
     */
    protected PreparedStatement proxyPreparedStatement(PreparedStatement delegate, Connection conn, String sql) throws SQLException {
        return proxyPreparedStatement(delegate, conn);
    }

    /**
     * Proxy a CallableStatement with access to the original SQL.
     * Override this method when you need to recreate the statement (e.g., on connection failure).
     * The default implementation ignores the SQL and delegates to {@link #proxyCallableStatement(CallableStatement, Connection)}.
     *
     * @param delegate the delegate CallableStatement
     * @param conn the connection
     * @param sql the SQL used to prepare the statement
     * @return the proxied CallableStatement
     * @throws SQLException if an error occurs
     */
    protected CallableStatement proxyCallableStatement(CallableStatement delegate, Connection conn, String sql) throws SQLException {
        return proxyCallableStatement(delegate, conn);
    }

    public ResultSet proxyResultSet(Statement stmt, ResultSet delegate) throws SQLException {
        if (delegate == null) return null;
        return new AbstractResultSet(stmt, delegate) {};
    }

    /**
     * Whether to automatically validate parameters on connect.
     * Subclasses can override to enable/disable validation.
     * @return true to validate parameters, false to skip validation
     */
    protected boolean isValidateParametersEnabled() {
        return true;
    }

    /**
     * Whether to automatically validate driver composition on connect.
     * Subclasses can override to enable/disable validation.
     * Can also be disabled via system property: -Dpjdbc.validation.composition=false
     * @return true to validate composition, false to skip validation
     */
    protected boolean isCompositionValidationEnabled() {
        return !"false".equalsIgnoreCase(System.getProperty("pjdbc.validation.composition", "true"));
    }

    @Override
    public Connection connect(String url, Properties info) throws SQLException {
        if (!acceptsURL(url)) return null;
        if (isCompositionValidationEnabled()) {
            CompositionValidator.standard().validate(url);
        }
        if (isValidateParametersEnabled()) {
            validateParameters(url);
        }
        return proxyConnection(DriverManager.getConnection(subname(url)), url, info, this);
    }

    @Override
    public DriverPropertyInfo[] getPropertyInfo(String url, Properties info) throws SQLException {
        if (!acceptsURL(url)) throw new SQLException("Invalid url:  " + url);
        Driver driver = DriverManager.getDriver(subname(url));
        if (driver == null) throw new SQLException("No valid target driver registered for:  " + subname(url));
        return driver.getPropertyInfo(subname(url), info);
    }
}
