package org.pjdbc.sql;

import java.sql.*;
import java.util.*;

public abstract class AbstractStatement extends AbstractWrapper implements Statement {
    private Connection conn;
    private List<Statement> delegates = new ArrayList<Statement>();

    /**
     * Strategy for merging results from multiple delegate statements.
     */
    public enum MergeStrategy {
        /** Return result from first (primary) delegate only */
        FIRST,
        /** Sum all update counts */
        SUM,
        /** Return minimum update count (conservative) */
        MIN,
        /** Return maximum update count */
        MAX
    }

    private MergeStrategy mergeStrategy = MergeStrategy.FIRST;

    protected List<Statement> getStatements () {
	return delegates;}

    protected ResultSet wrap (ResultSet r) throws SQLException {
	return new AbstractResultSet(this, r){};}

    public MergeStrategy getMergeStrategy() {
        return mergeStrategy;}

    public void setMergeStrategy(MergeStrategy strategy) {
        this.mergeStrategy = strategy;}

    protected int mergeUpdateCounts(List<Integer> counts) {
        if (counts.isEmpty()) return 0;
        switch (mergeStrategy) {
            case SUM:
                return counts.stream().mapToInt(Integer::intValue).sum();
            case MIN:
                return counts.stream().mapToInt(Integer::intValue).min().orElse(0);
            case MAX:
                return counts.stream().mapToInt(Integer::intValue).max().orElse(0);
            case FIRST:
            default:
                return counts.get(0);
        }
    }

    public AbstractStatement (Statement stmt, Connection conn) throws SQLException {
	super(stmt);
	delegates.add(stmt);
	this.conn = conn;}

    public AbstractStatement (Statement[] stmts, Connection conn) throws SQLException {
	super(stmts);
	delegates = Arrays.asList(stmts);
	this.conn = conn;}

    public Connection getConnection () throws SQLException {return conn;}
    public ResultSet executeQuery (String sql) throws SQLException {ArrayList<ResultSet> rsets = new ArrayList<ResultSet>(); for (Statement s : getStatements()) rsets.add(s.executeQuery(sql)); for (ResultSet r : rsets) return wrap(r); throw new SQLException();}
    public ResultSet getGeneratedKeys () throws SQLException {for (Statement s : getStatements()) return wrap(s.getGeneratedKeys()); throw new SQLException();}
    public ResultSet getResultSet () throws SQLException {for (Statement s : getStatements()) return wrap(s.getResultSet()); throw new SQLException();}
    public SQLWarning getWarnings () throws SQLException {for (Statement s : getStatements()) return s.getWarnings(); throw new SQLException();}
    public boolean execute (String sql) throws SQLException {Boolean first = null; for (Statement s : getStatements()) {boolean r = s.execute(sql); if (first == null) first = r;} if (first != null) return first; throw new SQLException();}
    public boolean execute (String sql, String[] columnNames) throws SQLException {Boolean first = null; for (Statement s : getStatements()) {boolean r = s.execute(sql, columnNames); if (first == null) first = r;} if (first != null) return first; throw new SQLException();}
    public boolean execute (String sql, int autoGeneratedKeys) throws SQLException {Boolean first = null; for (Statement s : getStatements()) {boolean r = s.execute(sql, autoGeneratedKeys); if (first == null) first = r;} if (first != null) return first; throw new SQLException();}
    public boolean execute (String sql, int[] columnIndexes) throws SQLException {Boolean first = null; for (Statement s : getStatements()) {boolean r = s.execute(sql, columnIndexes); if (first == null) first = r;} if (first != null) return first; throw new SQLException();}
    public boolean getMoreResults () throws SQLException {for (Statement s : getStatements()) return s.getMoreResults(); throw new SQLException();}
    public boolean getMoreResults (int current) throws SQLException {for (Statement s : getStatements()) return s.getMoreResults(current); throw new SQLException();}
    public boolean isCloseOnCompletion () throws SQLException {for (Statement s : getStatements()) return s.isCloseOnCompletion(); throw new SQLException();}
    public boolean isClosed () throws SQLException {for (Statement s : getStatements()) return s.isClosed(); throw new SQLException();}
    public boolean isPoolable () throws SQLException {for (Statement s : getStatements()) return s.isPoolable(); throw new SQLException();}
    public int executeUpdate (String sql) throws SQLException {List<Integer> counts = new ArrayList<>(); for (Statement s : getStatements()) counts.add(s.executeUpdate(sql)); if (!counts.isEmpty()) return mergeUpdateCounts(counts); throw new SQLException();}
    public int executeUpdate (String sql, String[] columnNames) throws SQLException {List<Integer> counts = new ArrayList<>(); for (Statement s : getStatements()) counts.add(s.executeUpdate(sql, columnNames)); if (!counts.isEmpty()) return mergeUpdateCounts(counts); throw new SQLException();}
    public int executeUpdate (String sql, int autoGeneratedKeys) throws SQLException {List<Integer> counts = new ArrayList<>(); for (Statement s : getStatements()) counts.add(s.executeUpdate(sql, autoGeneratedKeys)); if (!counts.isEmpty()) return mergeUpdateCounts(counts); throw new SQLException();}
    public int executeUpdate (String sql, int[] columnIndexes) throws SQLException {List<Integer> counts = new ArrayList<>(); for (Statement s : getStatements()) counts.add(s.executeUpdate(sql, columnIndexes)); if (!counts.isEmpty()) return mergeUpdateCounts(counts); throw new SQLException();}
    public int getFetchDirection () throws SQLException {for (Statement s : getStatements()) return s.getFetchDirection(); throw new SQLException();}
    public int getFetchSize () throws SQLException {for (Statement s : getStatements()) return s.getFetchSize(); throw new SQLException();}
    public int getMaxFieldSize () throws SQLException {for (Statement s : getStatements()) return s.getMaxFieldSize(); throw new SQLException();}
    public int getMaxRows () throws SQLException {for (Statement s : getStatements()) return s.getMaxRows(); throw new SQLException();}
    public int getQueryTimeout () throws SQLException {for (Statement s : getStatements()) return s.getQueryTimeout(); throw new SQLException();}
    public int getResultSetConcurrency () throws SQLException {for (Statement s : getStatements()) return s.getResultSetConcurrency(); throw new SQLException();}
    public int getResultSetHoldability () throws SQLException {for (Statement s : getStatements()) return s.getResultSetHoldability(); throw new SQLException();}
    public int getResultSetType () throws SQLException {for (Statement s : getStatements()) return s.getResultSetType(); throw new SQLException();}
    public int getUpdateCount () throws SQLException {for (Statement s : getStatements()) return s.getUpdateCount(); throw new SQLException();}
    public int[] executeBatch () throws SQLException {int[] first = null; for (Statement s : getStatements()) {int[] r = s.executeBatch(); if (first == null) first = r;} if (first != null) return first; throw new SQLException();}
    public void addBatch (String sql) throws SQLException {for (Statement s : getStatements()) s.addBatch(sql);}
    public void cancel () throws SQLException {for (Statement s : getStatements()) s.cancel();}
    public void clearBatch () throws SQLException {for (Statement s : getStatements()) s.clearBatch();}
    public void clearWarnings () throws SQLException {for (Statement s : getStatements()) s.clearWarnings();}
    public void close () throws SQLException {for (Statement s : getStatements()) s.close();}
    public void closeOnCompletion () throws SQLException {for (Statement s : getStatements()) s.closeOnCompletion();}
    public void setCursorName (String name) throws SQLException {for (Statement s : getStatements()) s.setCursorName(name);}
    public void setEscapeProcessing (boolean enable) throws SQLException {for (Statement s : getStatements()) s.setEscapeProcessing(enable);}
    public void setFetchDirection (int direction) throws SQLException {for (Statement s : getStatements()) s.setFetchDirection(direction);}
    public void setFetchSize (int rows) throws SQLException {for (Statement s : getStatements()) s.setFetchSize(rows);}
    public void setMaxFieldSize (int max) throws SQLException {for (Statement s : getStatements()) s.setMaxFieldSize(max);}
    public void setMaxRows (int max) throws SQLException {for (Statement s : getStatements()) s.setMaxRows(max);}
    public void setPoolable (boolean poolable) throws SQLException {for (Statement s : getStatements()) s.setPoolable(poolable);}
    public void setQueryTimeout (int seconds) throws SQLException {for (Statement s : getStatements()) s.setQueryTimeout(seconds);}}
