package org.pjdbc.sql;

import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Driver;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Properties;

/**
 * Base class for proxy connections that automatically delegates statement creation
 * to the driver's proxy methods. This eliminates ~60 lines of boilerplate per driver.
 *
 * <h2>Usage</h2>
 * <p>Extend this class in your driver and implement any custom behavior:</p>
 * <pre>
 * private class MyConnection extends ProxyConnection {
 *     private final MyConfig config;
 *
 *     MyConnection(Connection conn, AbstractProxyDriver driver, String url, Properties info) throws SQLException {
 *         super(conn, driver, url, info);
 *         this.config = new MyConfig(url);
 *     }
 *
 *     public MyConfig getConfig() { return config; }
 * }
 * </pre>
 *
 * <p>The driver must override the proxy methods (proxyStatement, proxyPreparedStatement,
 * proxyCallableStatement) to provide custom statement wrappers.</p>
 *
 * @see AbstractProxyDriver
 * @see AbstractConnection
 */
public class ProxyConnection extends AbstractConnection {

    private final AbstractProxyDriver proxyDriver;

    /**
     * Create a proxy connection.
     *
     * @param conn     the underlying connection
     * @param driver   the proxy driver (must be AbstractProxyDriver)
     * @param url      the JDBC URL
     * @param info     connection properties
     * @throws SQLException if connection setup fails
     */
    public ProxyConnection(Connection conn, AbstractProxyDriver driver, String url, Properties info) throws SQLException {
        super(conn, (Driver) driver, url, info);
        this.proxyDriver = driver;
    }

    /**
     * Get the proxy driver for subclass access.
     */
    protected AbstractProxyDriver getProxyDriver() {
        return proxyDriver;
    }

    // === Statement creation - delegates to driver's proxyStatement ===

    @Override
    public Statement createStatement() throws SQLException {
        return proxyDriver.proxyStatement(getDelegate().createStatement(), this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException {
        return proxyDriver.proxyStatement(getDelegate().createStatement(resultSetType, resultSetConcurrency), this);
    }

    @Override
    public Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return proxyDriver.proxyStatement(getDelegate().createStatement(resultSetType, resultSetConcurrency, resultSetHoldability), this);
    }

    // === PreparedStatement creation - delegates to driver's proxyPreparedStatement ===

    @Override
    public PreparedStatement prepareStatement(String sql) throws SQLException {
        return proxyDriver.proxyPreparedStatement(getDelegate().prepareStatement(sql), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
        return proxyDriver.proxyPreparedStatement(getDelegate().prepareStatement(sql, autoGeneratedKeys), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
        return proxyDriver.proxyPreparedStatement(getDelegate().prepareStatement(sql, columnIndexes), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return proxyDriver.proxyPreparedStatement(getDelegate().prepareStatement(sql, resultSetType, resultSetConcurrency), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return proxyDriver.proxyPreparedStatement(getDelegate().prepareStatement(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this);
    }

    @Override
    public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
        return proxyDriver.proxyPreparedStatement(getDelegate().prepareStatement(sql, columnNames), this);
    }

    // === CallableStatement creation - delegates to driver's proxyCallableStatement ===

    @Override
    public CallableStatement prepareCall(String sql) throws SQLException {
        return proxyDriver.proxyCallableStatement(getDelegate().prepareCall(sql), this);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
        return proxyDriver.proxyCallableStatement(getDelegate().prepareCall(sql, resultSetType, resultSetConcurrency), this);
    }

    @Override
    public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException {
        return proxyDriver.proxyCallableStatement(getDelegate().prepareCall(sql, resultSetType, resultSetConcurrency, resultSetHoldability), this);
    }
}
